.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scan 1 0.1.1 https://github.com/dbowm91/cargo-cleanme "General Commands Manual"
.SH NAME
scan
.SH SYNOPSIS
\fBscan\fR [\fB\-\-full\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIROOT\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-full\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIROOT\fR]

